name: Clean up workspace

on:
  push:
    branches:
      - main

jobs:
  cleanup:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Run cleanup script
      run: |
        # 清理临时文件和目录
        rm -rf ${{ github.workspace }}/temp/*
        rm -rf ${{ github.workspace }}/cache/*

        # 清理特定目录
        rm -rf ${{ github.workspace }}/path/to/specific/directory/*
        
        # 打印磁盘使用情况
        df -h
