- name: Clean up disk space
  run: |
    sudo rm -rf /usr/local/lib/android
    sudo rm -rf /opt/ghc
    sudo rm -rf /usr/share/dotnet
    sudo rm -rf /usr/share/swift
    sudo apt-get clean
    sudo rm -rf /var/lib/apt/lists/*
