name: CI Pipeline

on: []

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    # 检出代码
    - name: Checkout code
      uses: actions/checkout@v3

    # 清理磁盘空间
    - name: Clean up disk space
      run: |
        echo "Cleaning up disk space..."
        sudo rm -rf /usr/local/lib/android
        sudo rm -rf /opt/ghc
        sudo rm -rf /usr/share/dotnet
        sudo rm -rf /usr/share/swift
        sudo apt-get clean
        sudo rm -rf /var/lib/apt/lists/*
        df -h
