name: Cleanup and Reset Workflow Space

on:
  push:
    branches:
      - main

jobs:
  cleanup:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Clean workspace
      run: |
        echo "Before cleanup:"
        df -h
        
        # 删除工作空间中的所有文件
        rm -rf ${{ github.workspace }}/*
        
        echo "Workspace cleaned."
        
        # 清理 Docker 容器和镜像
        docker system prune -af --volumes
        
        echo "Docker cleaned."
        
        # 清理系统缓存和临时文件
        sudo rm -rf /var/cache/*
        sudo rm -rf /tmp/*
        
        # 清理日志文件
        sudo find /var/log -type f -delete
        
        echo "System cache, temporary files, and logs cleaned."

        # 打印清理后的磁盘使用情况
        echo "After cleanup:"
        df -h
